INSERT INTO Break_Point VALUES ('베히모스','뿔');
INSERT INTO Break_Point VALUES ('베히모스','앞다리');
INSERT INTO Break_Point VALUES ('베히모스','꼬리');
INSERT INTO Break_Point VALUES ('나나-테스카토리','머리');
INSERT INTO Break_Point VALUES ('나나-테스카토리','날개');
INSERT INTO Break_Point VALUES ('나나-테스카토리','꼬리');
INSERT INTO Break_Point VALUES ('맘-타로트','황금');
INSERT INTO Break_Point VALUES ('맘-타로트','큰뿔');
INSERT INTO Break_Point VALUES ('맘-타로트','꼬리');
INSERT INTO Break_Point VALUES ('이블조','머리');
INSERT INTO Break_Point VALUES ('이블조','몸통');
INSERT INTO Break_Point VALUES ('이블조','꼬리');
INSERT INTO Break_Point VALUES ('제노-지바','머리');
INSERT INTO Break_Point VALUES ('제노-지바','앞다리');
INSERT INTO Break_Point VALUES ('제노-지바','날개');
INSERT INTO Break_Point VALUES ('제노-지바','꼬리');
INSERT INTO Break_Point VALUES ('발하자크','머리');
INSERT INTO Break_Point VALUES ('발하자크','앞다리');
INSERT INTO Break_Point VALUES ('발하자크','몸통');
INSERT INTO Break_Point VALUES ('발하자크','꼬리');
INSERT INTO Break_Point VALUES ('크샬다오라','머리');
INSERT INTO Break_Point VALUES ('크샬다오라','날개');
INSERT INTO Break_Point VALUES ('크샬다오라','꼬리');
INSERT INTO Break_Point VALUES ('테오-테스카토르','머리');
INSERT INTO Break_Point VALUES ('테오-테스카토르','날개');
INSERT INTO Break_Point VALUES ('테오-테스카토르','꼬리');
INSERT INTO Break_Point VALUES ('네르기간테','뿔');
INSERT INTO Break_Point VALUES ('네르기간테','꼬리');
INSERT INTO Break_Point VALUES ('디아블로스 아종','뿔');
INSERT INTO Break_Point VALUES ('디아블로스 아종','등');
INSERT INTO Break_Point VALUES ('디아블로스 아종','꼬리');
INSERT INTO Break_Point VALUES ('리오레우스 아종','머리');
INSERT INTO Break_Point VALUES ('리오레우스 아종','날개');
INSERT INTO Break_Point VALUES ('리오레우스 아종','등');
INSERT INTO Break_Point VALUES ('리오레우스 아종','꼬리');
INSERT INTO Break_Point VALUES ('우라간킨','머리');
INSERT INTO Break_Point VALUES ('우라간킨','등');
INSERT INTO Break_Point VALUES ('우라간킨','꼬리');
INSERT INTO Break_Point VALUES ('볼가노스','머리');
INSERT INTO Break_Point VALUES ('볼가노스','몸통');
INSERT INTO Break_Point VALUES ('볼가노스','다리');
INSERT INTO Break_Point VALUES ('볼가노스','꼬리');
INSERT INTO Break_Point VALUES ('바젤기우스','머리');
INSERT INTO Break_Point VALUES ('바젤기우스','날개');
INSERT INTO Break_Point VALUES ('바젤기우스','등');
INSERT INTO Break_Point VALUES ('바젤기우스','꼬리');
INSERT INTO Break_Point VALUES ('리오레이아 아종','머리');
INSERT INTO Break_Point VALUES ('리오레이아 아종','날개');
INSERT INTO Break_Point VALUES ('리오레이아 아종','등');
INSERT INTO Break_Point VALUES ('리오레이아 아종','꼬리');
INSERT INTO Break_Point VALUES ('도도가마루','머리');
INSERT INTO Break_Point VALUES ('도도가마루','앞다리');
INSERT INTO Break_Point VALUES ('도도가마루','꼬리');
INSERT INTO Break_Point VALUES ('조라-마그다라오스','머리');
INSERT INTO Break_Point VALUES ('조라-마그다라오스','배열기관');
INSERT INTO Break_Point VALUES ('조라-마그다라오스','몸통');
INSERT INTO Break_Point VALUES ('키린','뿔');
INSERT INTO Break_Point VALUES ('디아블로스','뿔');
INSERT INTO Break_Point VALUES ('디아블로스','등');
INSERT INTO Break_Point VALUES ('디아블로스','꼬리');
INSERT INTO Break_Point VALUES ('리오레우스','머리');
INSERT INTO Break_Point VALUES ('리오레우스','날개');
INSERT INTO Break_Point VALUES ('리오레우스','등');
INSERT INTO Break_Point VALUES ('리오레우스','꼬리');
INSERT INTO Break_Point VALUES ('오도가론','머리');
INSERT INTO Break_Point VALUES ('오도가론','앞다리');
INSERT INTO Break_Point VALUES ('오도가론','다리');
INSERT INTO Break_Point VALUES ('오도가론','꼬리');
INSERT INTO Break_Point VALUES ('레이기에나','머리');
INSERT INTO Break_Point VALUES ('레이기에나','날개');
INSERT INTO Break_Point VALUES ('레이기에나','등');
INSERT INTO Break_Point VALUES ('레이기에나','꼬리');
INSERT INTO Break_Point VALUES ('라도발킨','머리');
INSERT INTO Break_Point VALUES ('라도발킨','등');
INSERT INTO Break_Point VALUES ('라도발킨','다리');
INSERT INTO Break_Point VALUES ('라도발킨','꼬리');
INSERT INTO Break_Point VALUES ('도스기르오스','머리');
INSERT INTO Break_Point VALUES ('도스기르오스','앞다리');
INSERT INTO Break_Point VALUES ('도스기르오스','꼬리');
INSERT INTO Break_Point VALUES ('파오우르무','목주머니');
INSERT INTO Break_Point VALUES ('파오우르무','날개');
INSERT INTO Break_Point VALUES ('파오우르무','등');
INSERT INTO Break_Point VALUES ('파오우르무','꼬리');
INSERT INTO Break_Point VALUES ('치치야크','머리');
INSERT INTO Break_Point VALUES ('리오레이아','머리');
INSERT INTO Break_Point VALUES ('리오레이아','날개');
INSERT INTO Break_Point VALUES ('리오레이아','등');
INSERT INTO Break_Point VALUES ('리오레이아','꼬리');
INSERT INTO Break_Point VALUES ('안쟈나프','머리');
INSERT INTO Break_Point VALUES ('안쟈나프','다리');
INSERT INTO Break_Point VALUES ('안쟈나프','꼬리');
INSERT INTO Break_Point VALUES ('토비카가치','머리');
INSERT INTO Break_Point VALUES ('토비카가치','앞다리');
INSERT INTO Break_Point VALUES ('토비카가치','등');
INSERT INTO Break_Point VALUES ('토비카가치','꼬리');
INSERT INTO Break_Point VALUES ('쥬라토도스','머리');
INSERT INTO Break_Point VALUES ('쥬라토도스','몸통');
INSERT INTO Break_Point VALUES ('쥬라토도스','다리');
INSERT INTO Break_Point VALUES ('쥬라토도스','꼬리');
INSERT INTO Break_Point VALUES ('볼보로스','머리');
INSERT INTO Break_Point VALUES ('볼보로스','앞다리');
INSERT INTO Break_Point VALUES ('볼보로스','다리');
INSERT INTO Break_Point VALUES ('볼보로스','꼬리');
INSERT INTO Break_Point VALUES ('푸케푸케','머리');
INSERT INTO Break_Point VALUES ('푸케푸케','날개');
INSERT INTO Break_Point VALUES ('푸케푸케','등');
INSERT INTO Break_Point VALUES ('푸케푸케','꼬리');
INSERT INTO Break_Point VALUES ('쿠루루야크','머리');
INSERT INTO Break_Point VALUES ('쿠루루야크','앞다리');
INSERT INTO Break_Point VALUES ('도스쟈그라스','머리');
INSERT INTO Break_Point VALUES ('도스쟈그라스','몸통');
INSERT INTO Break_Point VALUES ('도스쟈그라스','앞다리');