use db_project;

    
INSERT INTO Names_
values ('chichiyark',	'치치야크'),
		('pukepuke',	'푸케푸케'),
        ('kururuyark',	'쿠루루야크'),
        ('ebljo',		'이블조'),
        ('uragankin',	'우라간킨'),
        ('radobalkin',	'라도발킨'),
        ('anzyanaf',	'안쟈나프'),
        ('bolboros',	'볼보로스'),
        ('bolganos',	'볼가노스'),
        ('juratodos',	'쥬라토도스'),
        ('dodogamaru',	'도도가마루'),
        ('odogaron',	'오도가론'),
        ('dosgiros',	'도스기르오스'),
        ('tobikagachi',	'토비카가치'),
        ('doszyagras',	'도스쟈그라스'),
        ('diablos2',	'디아블로스 아종'),
        ('rioreus2',	'리오레우스 아종'),
        ('bazelgius',	'바젤기우스'),
        ('rioreia2',	'리오레이아 아종'),
        ('diablos',		'디아블로스'),
        ('rioreus',		'리오레우스'),
        ('reigiena',	'레이기에나'),
        ('paourumu',	'파오우르무'),
        ('rioreia',		'리오레이아'),
        ('behimos',		'베히모스'),
        ('nana-teskatori',	'나나-테스카토리'),
        ('mom-tarot',	'맘-타로트'),
        ('zeno-jiva',	'제노-지바'),
        ('balhazak',	'발하자크'),
        ('kushaldaora',	'크샬다오라'),
        ('teo-teskator','테오-테스카토르'),
        ('nergigante',	'네르기간테'),
        ('jora-magdaraos',	'조라-마그다라오스'),
        ('kirin',		'키린');
	