INSERT INTO Weak_Point VALUES ('베히모스','뿔');
INSERT INTO Weak_Point VALUES ('베히모스','꼬리');
INSERT INTO Weak_Point VALUES ('나나-테스카토리','날개');
INSERT INTO Weak_Point VALUES ('나나-테스카토리','머리');
INSERT INTO Weak_Point VALUES ('나나-테스카토리','꼬리');
INSERT INTO Weak_Point VALUES ('맘-타로트','황금');
INSERT INTO Weak_Point VALUES ('맘-타로트','큰뿔');
INSERT INTO Weak_Point VALUES ('이블조','머리');
INSERT INTO Weak_Point VALUES ('이블조','배');
INSERT INTO Weak_Point VALUES ('제노-지바','머리');
INSERT INTO Weak_Point VALUES ('제노-지바','꼬리');
INSERT INTO Weak_Point VALUES ('발하자크','꼬리');
INSERT INTO Weak_Point VALUES ('발하자크','머리');
INSERT INTO Weak_Point VALUES ('크샬다오라','머리');
INSERT INTO Weak_Point VALUES ('크샬다오라','꼬리');
INSERT INTO Weak_Point VALUES ('테오-테스카토르','머리');
INSERT INTO Weak_Point VALUES ('네르기간테','뿔/앞다리');
INSERT INTO Weak_Point VALUES ('네르기간테','머리');
INSERT INTO Weak_Point VALUES ('네르기간테','앞다리');
INSERT INTO Weak_Point VALUES ('디아블로스 아종','배');
INSERT INTO Weak_Point VALUES ('디아블로스 아종','머리');
INSERT INTO Weak_Point VALUES ('디아블로스 아종','날개');
INSERT INTO Weak_Point VALUES ('리오레우스 아종','머리');
INSERT INTO Weak_Point VALUES ('우라간킨','머리');
INSERT INTO Weak_Point VALUES ('볼가노스','머리');
INSERT INTO Weak_Point VALUES ('볼가노스','몸통');
INSERT INTO Weak_Point VALUES ('바젤기우스','머리');
INSERT INTO Weak_Point VALUES ('바젤기우스','날개');
INSERT INTO Weak_Point VALUES ('리오레이아 아종','머리');
INSERT INTO Weak_Point VALUES ('도도가마루','머리');
INSERT INTO Weak_Point VALUES ('조라-마그다라오스','배열기관');
INSERT INTO Weak_Point VALUES ('키린','머리');
INSERT INTO Weak_Point VALUES ('오도가론','머리');
INSERT INTO Weak_Point VALUES ('레이기에나','머리');
INSERT INTO Weak_Point VALUES ('라도발킨','머리');
INSERT INTO Weak_Point VALUES ('도스기르오스','머리');
INSERT INTO Weak_Point VALUES ('파오우르무','목주머니');
INSERT INTO Weak_Point VALUES ('치치야크','머리');
INSERT INTO Weak_Point VALUES ('안쟈나프','머리');
INSERT INTO Weak_Point VALUES ('토비카가치','꼬리');
INSERT INTO Weak_Point VALUES ('쥬라토도스','머리');
INSERT INTO Weak_Point VALUES ('쥬라토도스','꼬리');
INSERT INTO Weak_Point VALUES ('볼보로스','앞다리');
INSERT INTO Weak_Point VALUES ('푸케푸케','머리');
INSERT INTO Weak_Point VALUES ('쿠루루야크','머리');
INSERT INTO Weak_Point VALUES ('도스쟈그라스', '머리');
INSERT INTO Weak_Point VALUES ('도스쟈그라스','몸통');